//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBlog.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCBlog.Core.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount With Cero.
        /// </summary>
        public static string AmountWithCero {
            get {
                return ResourceManager.GetString("AmountWithCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to.
        /// </summary>
        public static string AreYouSureYouWant {
            get {
                return ResourceManager.GetString("AreYouSureYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Birthdate and Category can&apos;t be null..
        /// </summary>
        public static string BirthdateCategoryNotNull {
            get {
                return ResourceManager.GetString("BirthdateCategoryNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryRangeExists.
        /// </summary>
        public static string CategoryRangeExists {
            get {
                return ResourceManager.GetString("CategoryRangeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoyYearFromYearTo.
        /// </summary>
        public static string CategoyYearFromYearTo {
            get {
                return ResourceManager.GetString("CategoyYearFromYearTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca un comentario..
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From higher Date To.
        /// </summary>
        public static string DateFromDateTo {
            get {
                return ResourceManager.GetString("DateFromDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From higher Date To highet to {0} days.
        /// </summary>
        public static string DiferentDate {
            get {
                return ResourceManager.GetString("DiferentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca el correo electrónico correctamente o deje el campo vacío..
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error FK.
        /// </summary>
        public static string ErrorFK {
            get {
                return ResourceManager.GetString("ErrorFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve .
        /// </summary>
        public static string FailedToRetrieve {
            get {
                return ResourceManager.GetString("FailedToRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca el sitio web correctamente o deje el campo vacío..
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncorrectTextImagen..
        /// </summary>
        public static string IncorrectTextImagen {
            get {
                return ResourceManager.GetString("IncorrectTextImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Closed.
        /// </summary>
        public static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string LeastCharacters {
            get {
                return ResourceManager.GetString("LeastCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search filter brought {0} or more records.
        /// </summary>
        public static string MaxRows {
            get {
                return ResourceManager.GetString("MaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, escriba su nombre..
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Characters..
        /// </summary>
        public static string NoMoreCharacters {
            get {
                return ResourceManager.GetString("NoMoreCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}.
        /// </summary>
        public static string NumberBetween {
            get {
                return ResourceManager.GetString("NumberBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a date. .
        /// </summary>
        public static string OnlyDate {
            get {
                return ResourceManager.GetString("OnlyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Integer..
        /// </summary>
        public static string OnlyInteger {
            get {
                return ResourceManager.GetString("OnlyInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordConfirmationDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado del socio debe ser Activo o Suspendido para poder pagar cuotas..
        /// </summary>
        public static string PayActiveOrSuspended {
            get {
                return ResourceManager.GetString("PayActiveOrSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date can&apos;t be Lower {0:dd/MM/yyyy}..
        /// </summary>
        public static string PaymentDateLower {
            get {
                return ResourceManager.GetString("PaymentDateLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment day upper to today {0:dd/MM/yyyy}..
        /// </summary>
        public static string PaymentDayUpperToToday {
            get {
                return ResourceManager.GetString("PaymentDayUpperToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated partner.
        /// </summary>
        public static string RepeatedPartner {
            get {
                return ResourceManager.GetString("RepeatedPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories entered..
        /// </summary>
        public static string ThereAreNoCategories {
            get {
                return ResourceManager.GetString("ThereAreNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They were updated {0} of {1}..
        /// </summary>
        public static string TheyWereUpdated {
            get {
                return ResourceManager.GetString("TheyWereUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Big!.
        /// </summary>
        public static string ToBigFile {
            get {
                return ResourceManager.GetString("ToBigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is unsupported File!.
        /// </summary>
        public static string UnsupportedFile {
            get {
                return ResourceManager.GetString("UnsupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upgrade your browser, because your current browser lacks some new features we need!.
        /// </summary>
        public static string UpgradeYourBrowser {
            get {
                return ResourceManager.GetString("UpgradeYourBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is DNI.
        /// </summary>
        public static string UserNameDNI {
            get {
                return ResourceManager.GetString("UserNameDNI", resourceCulture);
            }
        }
    }
}
